PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

TARGET		= $(PKGNAME)

# list your .c or .cc files here
SRC_C		= 
SRC_CC          = wrapper_1.cc 

# list requirements of your program here
REQUIRES_LIBS   = libvcpu stdlibs libstdc++ libio-io 

include $(L4DIR)/mk/prog.mk
