PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

TARGET		= $(PKGNAME)

# list your .c or .cc files here
SRC_C		= 
SRC_CC          = wrapper_1.cc 
#SRC_CC 		= wrapper_c_interface.cc

# list requirements of your program here
REQUIRES_LIBS   = libvcpu stdlibs 

include $(L4DIR)/mk/prog.mk
